### ISSUE TITLE
Convert to meta-package

### ISSUE THREAD

**Issue by kdpsingh** [TidierOrg/Tidier.jl#114]
We are close to being ready to convert Tidier.jl to a meta-package that re-exports TidierData, TidierPlots, TidierCats, TidierStrings, and TidierDates.

Here is the checklist of things we need to figure out and work on:

- [x] Need to fix an issue where TidierCats cannot correctly register its functions as non-vectorized within the separately loaded TidierData package. This is a complex issue that involves fixing both TidierData and TidierCats, but I think I am close to having a solution.

- [x] Remove almost the entire package except for the main page, which re-exports all the base packages with compatability noted as `>=` designation for version numbers of underlying packages.

- [x] Redo README and docs so that they point to the individual packages -- we should add some simple examples to show how the packages work together but remove the current examples so that this isn't simply a replication of the TidierData docs.

**Comment by kdpsingh** [comment]
Resolved in #115.
